### ISSUE TITLE
Improve scenario parameter naming for clarity

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/bucket-brigade#53]
## Problem

The current scenario parameter names are terse and not immediately clear:

```rust
pub struct Scenario {
    pub beta: f32,        // Fire spread probability
    pub kappa: f32,       // Extinguish efficiency  
    pub a: f32,           // Reward per saved house
    pub l: f32,           // Penalty per ruined house
    pub c: f32,           // Work cost per night
    pub rho_ignite: f32,  // Initial burn fraction
    pub n_min: u32,       // Minimum nights
    pub p_spark: f32,     // Spark probability
    pub n_spark: u32,     // Spark duration
    pub num_agents: usize,
    pub a_own: f32,       // Value of owned house when saved
    pub a_neighbor: f32,  // Value of neighbor house when saved
}
```

Issues:
- Greek letters (`beta`, `kappa`, `rho`) require comments to understand
- Single letters (`a`, `l`, `c`) are not self-documenting
- Inconsistent naming: `p_spark` vs `beta` (both probabilities)
- Mix of naming conventions: `rho_ignite` vs `p_spark` vs `n_min`

## Proposed Solution

Rename parameters to be self-documenting:

```rust
pub struct Scenario {
    // Fire dynamics
    pub fire_spread_prob: f32,        // Probability fire spreads to neighbor (β)
    pub extinguish_efficiency: f32,   // Efficiency of firefighting (κ)
    pub initial_fire_fraction: f32,   // Fraction of houses burning at start (ρ)
    pub spontaneous_ignition_prob: f32, // Probability of random fire (p_spark)
    pub spontaneous_ignition_nights: u32, // How long sparks can occur (n_spark)
    
    // Rewards and costs
    pub team_reward_per_house: f32,   // Team reward for each saved house (A)
    pub team_penalty_per_house: f32,  // Team penalty for each ruined house (L)
    pub work_cost_per_night: f32,     // Cost to work one night (c)
    pub owned_house_value: f32,       // Individual reward for own house saved (a_own)
    pub neighbor_house_value: f32,    // Individual reward for neighbor house saved (a_neighbor)
    
    // Game structure
    pub min_nights: u32,              // Minimum nights before game can end
    pub num_agents: usize,            // Number of agents in game
}
```

## Benefits

1. ✅ **Self-documenting**: No need to look up Greek letters
2. ✅ **Consistent**: All parameters follow `snake_case` convention
3. ✅ **Groupable**: Related parameters are clearly grouped
4. ✅ **Searchable**: Can grep for "prob" to find all probabilities

### Files Requiring Updates

**Core Rust Implementation** (12 parameter occurrences):
- `bucket-brigade-core/src/scenarios.rs` - Struct definition (4 scenarios × 12 params)
- `bucket-brigade-core/src/engine.rs` - 41 references across implementation and tests
- `bucket-brigade-core/src/lib.rs` - Re-exports

**Language Bindings** (Breaking Change):
- `bucket-brigade-core/src/python.rs` - PyScenario constructor and getters (24 references)
- `bucket-brigade-core/src/wasm.rs` - WASM bindings if present

**Python Ecosystem** (60+ Python files):
- `bucket_brigade/envs/scenarios.py` - Python scenario definitions
- All agent implementations that reference scenario parameters
- Test files (`tests/test_*.py`)
- Training scripts (`scripts/train_*.py`, `scripts/evaluate_*.py`)

### Related Issues

⚠️ **Coordination with #52**: Issue #52 refactors the reward calculation system. This refactoring may affect `a_own` and `a_neighbor` parameters. Consider:
1. Completing #52 first, then applying this refactor
2. OR: Apply this refactor first to make #52's changes clearer
3. Check if reward parameters should be renamed differently based on #52's new architecture

### Core Implementation
- [ ] Scenario struct updated with new parameter names
- [ ] All 4 predefined scenarios (`trivial_cooperation`, `early_containment`, `greedy_neighbor`, `random`) updated
- [ ] All references in `engine.rs` updated (fire spread, extinguishing, rewards, sparks, termination)
- [ ] Comprehensive tests pass (16 existing tests in `scenarios.rs`, 14 in `engine.rs`)

### Language Bindings
- [ ] Python bindings updated (`PyScenario` constructor and all getters)
- [ ] WASM bindings updated if present
- [ ] Serialization/deserialization maintains compatibility (or migration path provided)

### Documentation
- [ ] Inline documentation updated
- [ ] Comments preserve Greek letter mappings for academic reference
- [ ] Migration guide added for external users

### Testing & Validation
- [ ] All existing Rust tests pass without modification
- [ ] Python integration tests pass (`test_rust_integration.py`)
- [ ] Serialization round-trip tests confirm JSON field names changed
- [ ] No performance regression (parameter access patterns unchanged)

### Approach 1: Direct Rename (Recommended)
**Pros**: Clean, simple, forces all code to update
**Cons**: Breaking change for external users

1. Update `Scenario` struct definition
2. Find/replace all references in Rust codebase
3. Update Python bindings with new parameter names
4. Update all Python code
5. Run full test suite
6. Update documentation

### Approach 2: Deprecation Path
**Pros**: Gradual migration, backward compatibility
**Cons**: More complex, temporary code duplication

1. Add new parameter names using `#[serde(alias = "old_name")]`
2. Keep old getters marked `#[deprecated]`
3. Update internal code to new names
4. Add deprecation warnings in Python bindings
5. Remove old names in v2.0.0

### Rust Tests
```bash
# Run core tests
cd bucket-brigade-core
cargo test

# Verify no compilation errors
cargo clippy -- -D warnings
```

### Python Integration Tests
```bash
# Test Python bindings work
python test_rust_core.py

# Test all agent implementations still work
pytest tests/test_agents.py

# Verify scenario loading
python scripts/test_scenarios.py
```

### Serialization Compatibility
```rust
#[test]
fn test_scenario_json_field_names() {
    let scenario = SCENARIOS.get("trivial_cooperation").unwrap();
    let json = serde_json::to_string(scenario).unwrap();
    
    // Verify new field names present
    assert!(json.contains("\"fire_spread_prob\":"));
    assert!(json.contains("\"extinguish_efficiency\":"));
    
    // Verify old field names absent
    assert!(!json.contains("\"beta\":"));
    assert!(!json.contains("\"kappa\":"));
}
```

### Risk 1: Breaking External Code
**Impact**: High - Any external code using scenarios will break
**Mitigation**: 
- Use serde aliases for backward-compatible deserialization
- Provide clear migration guide in release notes
- Consider semver major version bump

### Risk 2: Python/Rust Binding Mismatch
**Impact**: Medium - Python code may fail silently
**Mitigation**:
- Update bindings atomically in same commit
- Add integration tests covering all parameters
- Run full Python test suite before merge

### Risk 3: Incomplete Refactoring
**Impact**: Medium - Compilation errors or runtime bugs
**Mitigation**:
- Use compiler to find all references (`cargo build`)
- Grep for old parameter names before declaring done
- Comprehensive test coverage validates all code paths

### Risk 4: Merge Conflicts with #52
**Impact**: Low-Medium - Both touch reward parameters
**Mitigation**:
- Coordinate with #52 implementation
- Clearly define which issue handles which renames
- Consider doing this first (cleaner foundation for #52)

### Parameter Usage Locations (from grep analysis)

**Fire Dynamics**:
- `beta`: Line 177 in spread logic, 270 in observation, tests at 415, 440-441
- `kappa`: Line 154 in extinguish logic, 270 in observation, test at 415
- `rho_ignite`: Line 77 in reset, 275 in observation
- `p_spark`: Line 196 in spark logic, 277 in observation, tests at 478, 499
- `n_spark`: Line 118 in spark check, 278 in observation, tests at 479, 500

**Rewards**:
- `a`: Line 209 in team reward calculation, 272 in observation
- `l`: Line 209 in team penalty calculation, 273 in observation
- `c`: Line 219 in work cost, 274 in observation, test at 128
- `a_own`, `a_neighbor`: Not yet used in engine.rs (planned for #52?)

**Game Structure**:
- `n_min`: Line 242 in termination check, 276 in observation, tests at 522, 536, 550
- `num_agents`: Used throughout for array sizing

### Serde Compatibility Pattern

For backward-compatible deserialization:
```rust
#[derive(Deserialize)]
pub struct Scenario {
    #[serde(alias = "beta")]
    pub fire_spread_prob: f32,
    
    #[serde(alias = "kappa")]
    pub extinguish_efficiency: f32,
    
    // ... etc
}
```

This allows old JSON to deserialize but serializes with new names.

## Alternative Considered

**Keep Greek Letters with Better Documentation**:
- Add comprehensive parameter guide page
- Create visual diagram showing parameter effects
- Keep names short for mathematical clarity

**Rejected because**: Readability and maintainability outweigh terseness for a game simulation codebase.

## Definition of Done

- [ ] All Rust code compiles without warnings
- [ ] All Rust tests pass (30+ tests)
- [ ] Python bindings updated and functional
- [ ] Python integration tests pass
- [ ] No performance regression measured
- [ ] Documentation updated
- [ ] Migration guide provided (if needed)
- [ ] PR reviewed and approved
