### ISSUE TITLE
chore(wasm): wasm-pack 0.13.1 + wasm-bindgen 0.2.105 emits thin loader without class bindings

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/bucket-brigade#338]
## Context

PR #337 (WASM two-phase support, refs #331) surfaced a pre-existing toolchain issue: `wasm-pack build --target web` succeeds, but the generated `bucket-brigade-core/pkg/bucket_brigade_core.{js,d.ts}` is a thin loader — class bindings (`WasmBucketBrigade`, `WasmScenario`, etc.) are not emitted in the JS/TS shim.

**Curator reproduction (2026-05-18):** Confirmed reproducible on current `main` with `wasm-pack 0.13.1` + `wasm-bindgen 0.2.105`. Fresh `wasm-pack build --target web` produces:

- `pkg/bucket_brigade_core.d.ts` (31 lines, no class declarations — only `InitInput`/`InitOutput`/`initSync`/`__wbg_init`)
- `pkg/bucket_brigade_core.js` (114 lines, no class definitions, no `get_scenario`/`get_scenario_names` exports)
- `pkg/bucket_brigade_core_bg.wasm` is only **1039 bytes** — i.e. the WASM binary itself has no `#[wasm_bindgen]`-exported symbols (not just a JS-glue issue).

A stale `pkg/` from a previous build (with an older `WasmScenario` API still exposing `num_agents` as a constructor arg) is present in the working tree but gitignored, so a fresh local checkout reproduces the broken state immediately.

## Root cause (CONFIRMED)

**The `wasm` feature flag is not being passed to cargo.**

`bucket-brigade-core/src/lib.rs:9-10`:
```rust
#[cfg(feature = "wasm")]
pub mod wasm;
```

`bucket-brigade-core/Cargo.toml:14-21`:
```toml
[features]
default = []
wasm = ["wasm-bindgen"]
python = ["pyo3"]

[dependencies.wasm-bindgen]
version = "0.2"
optional = true
```

Without `--features wasm`, the `wasm` module is gated out, no `#[wasm_bindgen]` items are present, and wasm-pack still happily emits a "minimal" loader-only `pkg/`.

`scripts/cf-pages-build.sh:53` (production build for `bucket-brigade.rjwalters.info`):
```bash
(cd bucket-brigade-core && wasm-pack build --target web)
```
— **missing `--features wasm`**. This is the bug.

By contrast, `web/WASM.md` (lines 56, 145, 165, 182) documents the correct invocation `wasm-pack build --target web --features wasm`.

### Suspected causes — verdicts

1. ~~**Version skew** between wasm-pack and wasm-bindgen~~ — **Not the cause.** `0.13.1` + `0.2.105` resolve cleanly. (`wasm-pack` did print a soft-update notice for `0.15.0` but that's unrelated.)
2. ~~**`[lib] crate-type` config**~~ — **Not the cause.** `bucket-brigade-core/Cargo.toml:41` already has `crate-type = ["cdylib", "rlib"]`.
3. ~~**`#[wasm_bindgen]` macro syntax**~~ — **Not the cause.** All macros in `src/wasm.rs` (`#[wasm_bindgen]`, `#[wasm_bindgen(constructor)]`) are still valid in `0.2.105`.
4. ~~**Feature flag interaction between `python` and `wasm`**~~ — **Not the cause.** The opposite: the `wasm` feature is *never enabled* during `wasm-pack` because the build script doesn't pass it.

### Secondary bug surfaced

Once `--features wasm` is added, the build fails to compile (`src/wasm.rs:154`):
```
error[E0063]: missing field `commitment_mode` in initializer of `Scenario`
   --> src/wasm.rs:154:21
```
This was introduced by PR #321 (issue #252, two_phase commitment_mode): the new `Scenario.commitment_mode` field is referenced at `src/wasm.rs:43` but `WasmScenario::new` (`src/wasm.rs:140-216`) was not updated to populate it. Issue #331 ("extend two_phase commitment_mode to WASM") is already open to address the API surface for two-phase; that issue will likely subsume the constructor fix.

## The fix

Two-line change in `scripts/cf-pages-build.sh:53`:
```diff
-(cd bucket-brigade-core && wasm-pack build --target web)
+(cd bucket-brigade-core && wasm-pack build --target web --features wasm)
```

Plus fix the `commitment_mode` field initializer in `src/wasm.rs:154` (or wait for #331 to land, which must include this fix anyway).

Optionally: add a `bucket-brigade-core/build-wasm.sh` helper that mirrors the existing `build.sh` pattern (defensive `RUSTC_WRAPPER=` unset, version checks) and document the canonical invocation in a single place.

## Acceptance criteria

- [ ] `wasm-pack build --target web --features wasm` (run from `bucket-brigade-core/`) produces a `pkg/bucket_brigade_core.js` exporting `WasmBucketBrigade`, `WasmScenario`, `get_scenario`, `get_scenario_names`.
- [ ] `pkg/bucket_brigade_core.d.ts` includes type declarations for those exports.
- [ ] `pkg/bucket_brigade_core_bg.wasm` is materially larger than 1KB (the current broken build is 1039 bytes; a working build should be tens of KB minimum).
- [ ] `scripts/cf-pages-build.sh` passes `--features wasm`.
- [ ] CF Pages build at `bucket-brigade.rjwalters.info` regenerates a working `pkg/` rather than relying on cached output.
- [ ] (Coordinate with #331) `src/wasm.rs:154` `Scenario` initializer includes `commitment_mode: "simultaneous".to_string()` (or appropriate default).

## Affected Files

- `scripts/cf-pages-build.sh:53` — **primary fix**, add `--features wasm`.
- `bucket-brigade-core/src/wasm.rs:154` — secondary fix, add `commitment_mode` to initializer (may be handled by #331).
- `web/WASM.md` — already correct, no change needed; consider linking from build script.
- Optionally: new `bucket-brigade-core/build-wasm.sh` helper to mirror `build.sh` pattern.

## Test Plan

- [ ] `rm -rf bucket-brigade-core/pkg && cd bucket-brigade-core && wasm-pack build --target web --features wasm` succeeds.
- [ ] Grep `pkg/bucket_brigade_core.d.ts` for `class WasmBucketBrigade` — present.
- [ ] `cd web && pnpm run build` succeeds.
- [ ] End-to-end smoke: web UI loads a scenario via `WasmBucketBrigade` and renders correctly.
- [ ] Trigger a CF Pages deploy and verify the deployed `pkg/` includes class bindings.

## References

- Surfaced by PR #337 builder report.
- Related: #331 (extend two_phase to WASM) — will need the same `--features wasm` fix and must address the `commitment_mode` constructor gap.
- Related: #311 (CF Pages migration) — the deployed site at `bucket-brigade.rjwalters.info` likely works only via cached/older `pkg/` from before the `commitment_mode` field landed.
- `web/WASM.md` already documents the correct invocation (lines 56, 145, 165, 182).

**Comment by rjwalters** [comment]
Curating per user request
